### ISSUE TITLE
Add Termux Push Notification

### ISSUE THREAD

**Issue by mykeels** [mykeels/crypto-dip-alert#7]
Using [this module](https://www.npmjs.com/package/termux/v/1.0.1), and a `notifications/termux.notification.js` file, we can get the script to display a Push Notification on the User's Android Device.

**Comment by Adekoreday** [comment]
@mykeels on this

**Comment by mykeels** [comment]
How is this going? @Adekoreday

**Comment by Adekoreday** [comment]
I was working on this before something came up. I will raise a PR this week
